---
title: "ETS load data.Rmd"
author: "Quan Nguyen"
date: "Thursday, May 28, 2015"
output: html_document
---

### Load monthly CSV files from ETS and save as data frames

```{r}
library(xlsx)

this_month = "07"
this_year = "2015"
this_data_month = paste0(this_year, "-", this_month, "-01")
```

# All 

``` {r}
ifile = paste0("ETS-data/", this_year, "/CLUMEQ - " ,this_year, "-", this_month, ".xlsx")
ofile = paste0("ETS-rda/all_", this_year, "_", this_month, ".rda")              

data = read.xlsx(file=ifile, sheetName = "data", startRow = 2, colIndex = c(11,12), header=F)
```

``` {r}
names(data) = c("datetime", "kwh")
# Fix time read from Excel which sometimes became 0:59 instead of 1:00
data$datetime = round(data$datetime)
data$datetime = as.POSIXlt(data$datetime,format="%Y/%m/%d %H:%M")

data$year = as.Date(cut(as.Date(data$datetime), breaks="year"))
data$quarter = as.Date(cut(as.Date(data$datetime), breaks="quarter"))
data$month = as.Date(cut(as.Date(data$datetime), breaks="month"))
data$week = as.Date(cut(as.Date(data$datetime), breaks="week"))
data$day = as.Date(cut(as.Date(data$datetime), breaks="day"))
data$hour = as.POSIXlt(cut(as.POSIXlt(data$datetime,format="%Y-%m-%d %H:%M"), breaks="hour"), format="%Y-%m-%d %H:%M:%S")
data = data[data$day > "2013-01-01",]
#by(data, data$day, dim)
#by(data, data$month, dim)
saveRDS(data, file=ofile)
```

# Mechanical part

``` {r}
ifile = paste0("ETS-data/", this_year, "/CLUMEQ_MEC - " ,this_year, "-", this_month, ".xlsx")
ofile = paste0("ETS-rda/mec_", this_year, "_", this_month, ".rda")              

data = read.xlsx(file=ifile, sheetName = "data", startRow = 2, colIndex = c(11,12), header=F)
```

``` {r}
names(data) = c("datetime", "kwh")
# Fix time read from Excel which sometimes became 0:59 instead of 1:00
data$datetime = round(data$datetime)
data$datetime = as.POSIXlt(data$datetime,format="%Y/%m/%d %H:%M")

data$year = as.Date(cut(as.Date(data$datetime), breaks="year"))
data$quarter = as.Date(cut(as.Date(data$datetime), breaks="quarter"))
data$month = as.Date(cut(as.Date(data$datetime), breaks="month"))
data$week = as.Date(cut(as.Date(data$datetime), breaks="week"))
data$day = as.Date(cut(as.Date(data$datetime), breaks="day"))
data$hour = as.POSIXlt(cut(as.POSIXlt(data$datetime,format="%Y-%m-%d %H:%M"), breaks="hour"), format="%Y-%m-%d %H:%M:%S")
data = data[data$day > "2013-01-01",]
#by(data, data$day, dim)
#by(data, data$month, dim)
saveRDS(data, file=ofile)
```