---
title: "Node consumption"
author: "Quan Nguyen"
date: "Tuesday, October 21, 2014"
output: html_document
---
Load the dataset
```{r}
data = read.csv("C:/Users/Quan Nguyen/OneDrive/Workbench/R/Projects/CLUMEQ power/summary-v2-2014_11_23_20")

names(data)
attach(data)
```

###Compare by category of servers

```{r fig.width=12, fig.height=12}
boxplot(data$WATT ~ data$CATEGORY)
```

###Summary Statistics

```{r}
# Total WATTs
sum(WATT)
# number of nodes per category
table(CATEGORY)
# total WATTs per row
tapply(WATT,ROW,sum)
# total WATTs per category
tapply(WATT,CATEGORY,sum)
# total WATTs per rack
tapply(WATT,RACK,sum)
# total WATTs per row and rack
tapply(WATT,list(CATEGORY,RACK),sum)   
# 
by(data,list(ROW),function(x) {
  y=subset(x)
  tapply(x$WATT,x$RACK,sum)
})

# total BTUs per category
tapply(BTU,CATEGORY,sum)
# total WATTs per rack
tapply(BTU,RACK,sum)
sum(BTU)
# BTU/WATT
sum(BTU)/sum(WATT)
```

###Compare BTU vs WATT

```{r}
cor(BTU, WATT)
fit <- lm(BTU ~ WATT)
summary(fit)
plot(fit)
plot(BTU ~ WATT)
```


